global:
  scrape_interval: 10s     # ค่าควร >= scrape_timeout
  scrape_timeout: 10s      # ค่าควร <= scrape_interval
  evaluation_interval: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []
      scheme: http
      timeout: 10s
      api_version: v2

scrape_configs:
  - job_name: prometheus
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: "job-node-exporter"
    scrape_interval: 9s
    static_configs:
      - targets: [ "node-exporter:9100" ]